cookie:
  expiry_days: 30
  key: sustain40_bioengine_key
  name: sustain40_cookie
credentials:
  usernames:
    admin:
      email: admin@bioengine.com
      name: Administrador
      password: $2b$12$Oa5Olnt3gVAL47KsCbDCc.m9NqbCMhJTHBgKj/6ms.yepDXMn9lqa
    demo:
      email: demo@bioengine.com
      name: Demo User
      password: $2b$12$vSQrAF95wa1RK8dnZZWDseeQ148R/1lBmvfUTgRmZdVICCg5SkKXS
preauthorized:
  emails:
  - admin@bioengine.com
